apiVersion: v1
kind: Service
metadata:
  name: private-gpt
  namespace: private-gpt
  labels:
    app: private-gpt
spec:
  type: ClusterIP
  selector:
    app: private-gpt
  ports:
  - name: http
    port: 80
    targetPort: 8001
    protocol: TCP
